// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// [Google Cloud Endpoints](https://cloud.google.com/appengine/docs/python/endpoints/)
/// configuration for API handlers.
public struct ApiConfigHandler: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Action to take when users access resources that require
  /// authentication. Defaults to `redirect`.
  public var authFailAction: AuthFailAction = AuthFailAction()

  /// Level of login required to access this resource. Defaults to
  /// `optional`.
  public var login: LoginRequirement = LoginRequirement()

  /// Path to the script from the application root directory.
  public var script: Swift.String = Swift.String()

  /// Security (HTTPS) enforcement for this URL.
  public var securityLevel: SecurityLevel = SecurityLevel()

  /// URL to serve the endpoint at.
  public var url: Swift.String = Swift.String()

  /// Initialize a new instance of `ApiConfigHandler`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ApiConfigHandler().with { $0.authFailAction = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.ApiConfigHandler"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
