// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An Application resource contains the top-level configuration of an App
/// Engine application.
public struct Application: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Full path to the Application resource in the API.
  /// Example: `apps/myapp`.
  ///
  /// @OutputOnly
  public var name: Swift.String = Swift.String()

  /// Identifier of the Application resource. This identifier is equivalent
  /// to the project ID of the Google Cloud Platform project where you want to
  /// deploy your application.
  /// Example: `myapp`.
  public var id: Swift.String = Swift.String()

  /// HTTP path dispatch rules for requests to the application that do not
  /// explicitly target a service or version. Rules are order-dependent.
  /// Up to 20 dispatch rules can be supported.
  public var dispatchRules: [UrlDispatchRule] = []

  /// Google Apps authentication domain that controls which users can access
  /// this application.
  ///
  /// Defaults to open access for any Google Account.
  public var authDomain: Swift.String = Swift.String()

  /// Location from which this application runs. Application instances
  /// run out of the data centers in the specified location, which is also where
  /// all of the application's end user content is stored.
  ///
  /// Defaults to `us-central`.
  ///
  /// View the list of
  /// [supported locations](https://cloud.google.com/appengine/docs/locations).
  public var locationId: Swift.String = Swift.String()

  /// Google Cloud Storage bucket that can be used for storing files
  /// associated with this application. This bucket is associated with the
  /// application and can be used by the gcloud deployment commands.
  ///
  /// @OutputOnly
  public var codeBucket: Swift.String = Swift.String()

  /// Cookie expiration policy for this application.
  public var defaultCookieExpiration: GoogleCloudWkt.Duration? = nil

  /// Serving status of this application.
  public var servingStatus: Application.ServingStatus = Application.ServingStatus()

  /// Hostname used to reach this application, as resolved by App Engine.
  ///
  /// @OutputOnly
  public var defaultHostname: Swift.String = Swift.String()

  /// Google Cloud Storage bucket that can be used by this application to store
  /// content.
  ///
  /// @OutputOnly
  public var defaultBucket: Swift.String = Swift.String()

  /// The service account associated with the application.
  /// This is the app-level default identity. If no identity provided during
  /// create version, Admin API will fallback to this one.
  public var serviceAccount: Swift.String = Swift.String()

  public var iap: Application.IdentityAwareProxy? = nil

  /// The Google Container Registry domain used for storing managed build docker
  /// images for this application.
  public var gcrDomain: Swift.String = Swift.String()

  /// The type of the Cloud Firestore or Cloud Datastore database associated with
  /// this application.
  public var databaseType: Application.DatabaseType = Application.DatabaseType()

  /// The feature specific settings to be used in the application.
  public var featureSettings: Application.FeatureSettings? = nil

  /// Initialize a new instance of `Application`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Application().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Identity-Aware Proxy
  public struct IdentityAwareProxy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Whether the serving infrastructure will authenticate and
    /// authorize all incoming requests.
    ///
    /// If true, the `oauth2_client_id` and `oauth2_client_secret`
    /// fields must be non-empty.
    public var enabled: Swift.Bool = Swift.Bool()

    /// OAuth2 client ID to use for the authentication flow.
    public var oauth2ClientId: Swift.String = Swift.String()

    /// OAuth2 client secret to use for the authentication flow.
    ///
    /// For security reasons, this value cannot be retrieved via the API.
    /// Instead, the SHA-256 hash of the value is returned in the
    /// `oauth2_client_secret_sha256` field.
    ///
    /// @InputOnly
    public var oauth2ClientSecret: Swift.String = Swift.String()

    /// Hex-encoded SHA-256 hash of the client secret.
    ///
    /// @OutputOnly
    public var oauth2ClientSecretSha256: Swift.String = Swift.String()

    /// Initialize a new instance of `IdentityAwareProxy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IdentityAwareProxy().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.appengine.v1.Application.IdentityAwareProxy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The feature specific settings to be used in the application. These define
  /// behaviors that are user configurable.
  public struct FeatureSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Boolean value indicating if split health checks should be used instead
    /// of the legacy health checks. At an app.yaml level, this means defaulting
    /// to 'readiness_check' and 'liveness_check' values instead of
    /// 'health_check' ones. Once the legacy 'health_check' behavior is
    /// deprecated, and this value is always true, this setting can
    /// be removed.
    public var splitHealthChecks: Swift.Bool = Swift.Bool()

    /// If true, use [Container-Optimized OS](https://cloud.google.com/container-optimized-os/)
    /// base image for VMs, rather than a base Debian image.
    public var useContainerOptimizedOs: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `FeatureSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FeatureSettings().with { $0.splitHealthChecks = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.appengine.v1.Application.FeatureSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum ServingStatus: Codable, Equatable, Sendable {
    /// Serving status is unspecified.
    case unspecified
    /// Application is serving.
    case serving
    /// Application has been disabled by the user.
    case userDisabled
    /// Application has been disabled by the system.
    case systemDisabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .serving: return 1
      case .userDisabled: return 2
      case .systemDisabled: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .serving: return "SERVING"
      case .userDisabled: return "USER_DISABLED"
      case .systemDisabled: return "SYSTEM_DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ServingStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "SERVING": self = .serving
      case "USER_DISABLED": self = .userDisabled
      case "SYSTEM_DISABLED": self = .systemDisabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ServingStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .serving
      case 2: self = .userDisabled
      case 3: self = .systemDisabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .serving: return try container.encode(1)
      case .userDisabled: return try container.encode(2)
      case .systemDisabled: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum DatabaseType: Codable, Equatable, Sendable {
    /// Database type is unspecified.
    case unspecified
    /// Cloud Datastore
    case cloudDatastore
    /// Cloud Firestore Native
    case cloudFirestore
    /// Cloud Firestore in Datastore Mode
    case cloudDatastoreCompatibility
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cloudDatastore: return 1
      case .cloudFirestore: return 2
      case .cloudDatastoreCompatibility: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATABASE_TYPE_UNSPECIFIED"
      case .cloudDatastore: return "CLOUD_DATASTORE"
      case .cloudFirestore: return "CLOUD_FIRESTORE"
      case .cloudDatastoreCompatibility: return "CLOUD_DATASTORE_COMPATIBILITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DatabaseType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATABASE_TYPE_UNSPECIFIED": self = .unspecified
      case "CLOUD_DATASTORE": self = .cloudDatastore
      case "CLOUD_FIRESTORE": self = .cloudFirestore
      case "CLOUD_DATASTORE_COMPATIBILITY": self = .cloudDatastoreCompatibility
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DatabaseType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cloudDatastore
      case 2: self = .cloudFirestore
      case 3: self = .cloudDatastoreCompatibility
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cloudDatastore: return try container.encode(1)
      case .cloudFirestore: return try container.encode(2)
      case .cloudDatastoreCompatibility: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Application"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
