// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleCloudGax

/// Manages SSL certificates a user is authorized to administer. A user can
/// administer any SSL certificates applicable to their authorized domains.
///
/// @Snippet(path: "AuthorizedCertificatesQuickstart")
public final class AuthorizedCertificatesClient: Clients.AuthorizedCertificatesProtocol, Sendable {
  let inner: any Clients.AuthorizedCertificatesStub

  /// Creates a new `AuthorizedCertificatesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AuthorizedCertificatesStub = try Clients.AuthorizedCertificatesTransport(
      options)
    inner = Clients.AuthorizedCertificatesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AuthorizedCertificatesLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists all SSL certificates the user is authorized to administer.
  ///
  /// @Snippet(path: "AuthorizedCertificates_ListAuthorizedCertificates")
  public func listAuthorizedCertificates(
    request: ListAuthorizedCertificatesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse {
    try await self.inner.listAuthorizedCertificates(request: request, options: options)
  }

  /// Lists all SSL certificates the user is authorized to administer.
  ///
  /// @Snippet(path: "AuthorizedCertificates_ListAuthorizedCertificates")
  public func listAuthorizedCertificates(
    byItem: ListAuthorizedCertificatesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AuthorizedCertificate, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAuthorizedCertificates(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the specified SSL certificate.
  ///
  /// @Snippet(path: "AuthorizedCertificates_GetAuthorizedCertificate")
  public func getAuthorizedCertificate(
    request: GetAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.AuthorizedCertificate {
    try await self.inner.getAuthorizedCertificate(request: request, options: options)
  }

  /// Uploads the specified SSL certificate.
  ///
  /// @Snippet(path: "AuthorizedCertificates_CreateAuthorizedCertificate")
  public func createAuthorizedCertificate(
    request: CreateAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.AuthorizedCertificate {
    try await self.inner.createAuthorizedCertificate(request: request, options: options)
  }

  /// Updates the specified SSL certificate. To renew a certificate and maintain
  /// its existing domain mappings, update `certificate_data` with a new
  /// certificate. The new certificate must be applicable to the same domains as
  /// the original certificate. The certificate `display_name` may also be
  /// updated.
  ///
  /// @Snippet(path: "AuthorizedCertificates_UpdateAuthorizedCertificate")
  public func updateAuthorizedCertificate(
    request: UpdateAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.AuthorizedCertificate {
    try await self.inner.updateAuthorizedCertificate(request: request, options: options)
  }

  /// Deletes the specified SSL certificate.
  ///
  /// @Snippet(path: "AuthorizedCertificates_DeleteAuthorizedCertificate")
  public func deleteAuthorizedCertificate(
    request: DeleteAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteAuthorizedCertificate(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuthorizedCertificates_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuthorizedCertificates_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AuthorizedCertificates_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AuthorizedCertificatesClient`.
  ///
  /// To mock `AuthorizedCertificatesClient` change your functions to receive
  /// `some AuthorizedCertificatesProtocol` or `any AuthorizedCertificatesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AuthorizedCertificatesProtocol {
    /// See `AuthorizedCertificatesClient.listAuthorizedCertificates`.
    func listAuthorizedCertificates(request: ListAuthorizedCertificatesRequest) async throws
      -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse

    /// See `AuthorizedCertificatesClient.listAuthorizedCertificates`.
    func listAuthorizedCertificates(
      byItem: ListAuthorizedCertificatesRequest
    ) throws -> any AsyncSequence<AuthorizedCertificate, Swift.Error>

    /// See `AuthorizedCertificatesClient.getAuthorizedCertificate`.
    func getAuthorizedCertificate(request: GetAuthorizedCertificateRequest) async throws
      -> GoogleAppEngineV1.AuthorizedCertificate

    /// See `AuthorizedCertificatesClient.createAuthorizedCertificate`.
    func createAuthorizedCertificate(request: CreateAuthorizedCertificateRequest) async throws
      -> GoogleAppEngineV1.AuthorizedCertificate

    /// See `AuthorizedCertificatesClient.updateAuthorizedCertificate`.
    func updateAuthorizedCertificate(request: UpdateAuthorizedCertificateRequest) async throws
      -> GoogleAppEngineV1.AuthorizedCertificate

    /// See `AuthorizedCertificatesClient.deleteAuthorizedCertificate`.
    func deleteAuthorizedCertificate(request: DeleteAuthorizedCertificateRequest) async throws

    /// See `AuthorizedCertificatesClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `AuthorizedCertificatesClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuthorizedCertificatesClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `AuthorizedCertificatesClient.listAuthorizedCertificates`.
    func listAuthorizedCertificates(
      request: ListAuthorizedCertificatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse

    /// See `AuthorizedCertificatesClient.listAuthorizedCertificates`.
    func listAuthorizedCertificates(
      byItem: ListAuthorizedCertificatesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AuthorizedCertificate, Swift.Error>

    /// See `AuthorizedCertificatesClient.getAuthorizedCertificate`.
    func getAuthorizedCertificate(
      request: GetAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.AuthorizedCertificate

    /// See `AuthorizedCertificatesClient.createAuthorizedCertificate`.
    func createAuthorizedCertificate(
      request: CreateAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.AuthorizedCertificate

    /// See `AuthorizedCertificatesClient.updateAuthorizedCertificate`.
    func updateAuthorizedCertificate(
      request: UpdateAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.AuthorizedCertificate

    /// See `AuthorizedCertificatesClient.deleteAuthorizedCertificate`.
    func deleteAuthorizedCertificate(
      request: DeleteAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AuthorizedCertificatesClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `AuthorizedCertificatesClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.AuthorizedCertificatesProtocol {
  public func listAuthorizedCertificates(request: ListAuthorizedCertificatesRequest) async throws
    -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse
  {
    try await self.listAuthorizedCertificates(request: request, options: .init())
  }

  public func listAuthorizedCertificates(
    request: ListAuthorizedCertificatesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAuthorizedCertificates(
    byItem: ListAuthorizedCertificatesRequest
  ) throws -> any AsyncSequence<AuthorizedCertificate, Swift.Error> {
    try self.listAuthorizedCertificates(byItem: byItem, options: .init())
  }

  public func listAuthorizedCertificates(
    byItem: ListAuthorizedCertificatesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AuthorizedCertificate, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleAppEngineV1.ListAuthorizedCertificatesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getAuthorizedCertificate(request: GetAuthorizedCertificateRequest) async throws
    -> GoogleAppEngineV1.AuthorizedCertificate
  {
    try await self.getAuthorizedCertificate(request: request, options: .init())
  }

  public func getAuthorizedCertificate(
    request: GetAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.AuthorizedCertificate {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAuthorizedCertificate(request: CreateAuthorizedCertificateRequest) async throws
    -> GoogleAppEngineV1.AuthorizedCertificate
  {
    try await self.createAuthorizedCertificate(request: request, options: .init())
  }

  public func createAuthorizedCertificate(
    request: CreateAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.AuthorizedCertificate {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAuthorizedCertificate(request: UpdateAuthorizedCertificateRequest) async throws
    -> GoogleAppEngineV1.AuthorizedCertificate
  {
    try await self.updateAuthorizedCertificate(request: request, options: .init())
  }

  public func updateAuthorizedCertificate(
    request: UpdateAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.AuthorizedCertificate {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAuthorizedCertificate(request: DeleteAuthorizedCertificateRequest) async throws
  {
    try await self.deleteAuthorizedCertificate(request: request, options: .init())
  }

  public func deleteAuthorizedCertificate(
    request: DeleteAuthorizedCertificateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
