// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax

/// Manages domains a user is authorized to administer. To authorize use of a
/// domain, verify ownership via
/// [Webmaster Central](https://www.google.com/webmasters/verification/home).
///
/// @Snippet(path: "AuthorizedDomainsQuickstart")
public class AuthorizedDomainsClient: Clients.AuthorizedDomainsProtocol {
  let inner: any Clients.AuthorizedDomainsStub

  /// Creates a new `AuthorizedDomainsClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AuthorizedDomainsStub = try Clients.AuthorizedDomainsTransport(options)
    inner = Clients.AuthorizedDomainsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AuthorizedDomainsLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists all domains the user is authorized to administer.
  ///
  /// @Snippet(path: "AuthorizedDomains_ListAuthorizedDomains")
  public func listAuthorizedDomains(
    request: ListAuthorizedDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppengineV1.ListAuthorizedDomainsResponse {
    try await self.inner.listAuthorizedDomains(request: request, options: options)
  }

  /// Lists all domains the user is authorized to administer.
  ///
  /// @Snippet(path: "AuthorizedDomains_ListAuthorizedDomains")
  public func listAuthorizedDomains(
    byItem: ListAuthorizedDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AuthorizedDomain, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleAppengineV1.ListAuthorizedDomainsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAuthorizedDomains(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuthorizedDomains_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuthorizedDomains_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "AuthorizedDomains_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AuthorizedDomainsClient`.
  ///
  /// To mock `AuthorizedDomainsClient` change your functions to receive
  /// `some AuthorizedDomainsProtocol` or `any AuthorizedDomainsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AuthorizedDomainsProtocol {
    /// See `AuthorizedDomainsClient.listAuthorizedDomains`.
    func listAuthorizedDomains(request: ListAuthorizedDomainsRequest) async throws
      -> GoogleAppengineV1.ListAuthorizedDomainsResponse

    /// See `AuthorizedDomainsClient.listAuthorizedDomains`.
    func listAuthorizedDomains(
      byItem: ListAuthorizedDomainsRequest
    ) throws -> any AsyncSequence<AuthorizedDomain, Swift.Error>

    /// See `AuthorizedDomainsClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `AuthorizedDomainsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `AuthorizedDomainsClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `AuthorizedDomainsClient.listAuthorizedDomains`.
    func listAuthorizedDomains(
      request: ListAuthorizedDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppengineV1.ListAuthorizedDomainsResponse

    /// See `AuthorizedDomainsClient.listAuthorizedDomains`.
    func listAuthorizedDomains(
      byItem: ListAuthorizedDomainsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AuthorizedDomain, Swift.Error>

    /// See `AuthorizedDomainsClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `AuthorizedDomainsClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.AuthorizedDomainsProtocol {
  public func listAuthorizedDomains(request: ListAuthorizedDomainsRequest) async throws
    -> GoogleAppengineV1.ListAuthorizedDomainsResponse
  {
    try await self.listAuthorizedDomains(request: request, options: .init())
  }

  public func listAuthorizedDomains(
    request: ListAuthorizedDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppengineV1.ListAuthorizedDomainsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAuthorizedDomains(
    byItem: ListAuthorizedDomainsRequest
  ) throws -> any AsyncSequence<AuthorizedDomain, Swift.Error> {
    try self.listAuthorizedDomains(byItem: byItem, options: .init())
  }

  public func listAuthorizedDomains(
    byItem: ListAuthorizedDomainsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AuthorizedDomain, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleAppengineV1.ListAuthorizedDomainsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
