// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An SSL certificate obtained from a certificate authority.
public struct CertificateRawData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// PEM encoded x.509 public key certificate. This field is set once on
  /// certificate creation. Must include the header and footer. Example:
  /// <pre>
  /// -----BEGIN CERTIFICATE-----
  /// <certificate_value>
  /// -----END CERTIFICATE-----
  /// </pre>
  public var publicCertificate: Swift.String = Swift.String()

  /// Unencrypted PEM encoded RSA private key. This field is set once on
  /// certificate creation and then encrypted. The key size must be 2048
  /// bits or fewer. Must include the header and footer. Example:
  /// <pre>
  /// -----BEGIN RSA PRIVATE KEY-----
  /// <unencrypted_key_value>
  /// -----END RSA PRIVATE KEY-----
  /// </pre>
  /// @InputOnly
  public var privateKey: Swift.String = Swift.String()

  /// Initialize a new instance of `CertificateRawData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateRawData().with { $0.publicCertificate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.CertificateRawData"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
