// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for `Firewall.CreateIngressRule`.
public struct CreateIngressRuleRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the parent Firewall collection in which to create a new rule.
  /// Example: `apps/myapp/firewall/ingressRules`.
  public var parent: Swift.String = Swift.String()

  /// A FirewallRule containing the new resource.
  ///
  /// The user may optionally provide a position at which the new rule will be
  /// placed. The positions define a sequential list starting at 1. If a rule
  /// already exists at the given position, rules greater than the provided
  /// position will be moved forward by one.
  ///
  /// If no position is provided, the server will place the rule as the second to
  /// last rule in the sequence before the required default allow-all or deny-all
  /// rule.
  public var rule: FirewallRule? = nil

  /// Initialize a new instance of `CreateIngressRuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateIngressRuleRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.CreateIngressRuleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
