// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Code and application artifacts used to deploy a version to App Engine.
public struct Deployment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Manifest of the files stored in Google Cloud Storage that are included
  /// as part of this version. All files must be readable using the
  /// credentials supplied with this call.
  public var files: [Swift.String: FileInfo] = [:]

  /// The Docker image for the container that runs the version.
  /// Only applicable for instances running in the App Engine flexible environment.
  public var container: ContainerInfo? = nil

  /// The zip file for this deployment, if this is a zip deployment.
  public var zip: ZipInfo? = nil

  /// Options for any Google Cloud Build builds created as a part of this
  /// deployment.
  ///
  /// These options will only be used if a new build is created, such as when
  /// deploying to the App Engine flexible environment using files or zip.
  public var cloudBuildOptions: CloudBuildOptions? = nil

  /// Initialize a new instance of `Deployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Deployment().with { $0.files = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Deployment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
