// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Target scaling by disk usage.
/// Only applicable in the App Engine flexible environment.
public struct DiskUtilization: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Target bytes written per second.
  public var targetWriteBytesPerSecond: Swift.Int32 = Swift.Int32()

  /// Target ops written per second.
  public var targetWriteOpsPerSecond: Swift.Int32 = Swift.Int32()

  /// Target bytes read per second.
  public var targetReadBytesPerSecond: Swift.Int32 = Swift.Int32()

  /// Target ops read per seconds.
  public var targetReadOpsPerSecond: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `DiskUtilization`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiskUtilization().with { $0.targetWriteBytesPerSecond = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.DiskUtilization"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
