// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A domain serving an App Engine application.
public struct DomainMapping: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Full path to the `DomainMapping` resource in the API. Example:
  /// `apps/myapp/domainMapping/example.com`.
  ///
  /// @OutputOnly
  public var name: Swift.String = Swift.String()

  /// Relative name of the domain serving the application. Example:
  /// `example.com`.
  public var id: Swift.String = Swift.String()

  /// SSL configuration for this domain. If unconfigured, this domain will not
  /// serve with SSL.
  public var sslSettings: SslSettings? = nil

  /// The resource records required to configure this domain mapping. These
  /// records must be added to the domain's DNS configuration in order to
  /// serve the application via this domain mapping.
  ///
  /// @OutputOnly
  public var resourceRecords: [ResourceRecord] = []

  /// Initialize a new instance of `DomainMapping`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DomainMapping().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.appengine.v1.DomainMapping"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
