// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class DomainMappingsLogging: DomainMappingsStub {
    let inner: any DomainMappingsStub
    let logger: Logger

    public init(_ inner: any DomainMappingsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-appengine-v1"
      logger[metadataKey: "gcp.client.service"] = "appengine"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DomainMappings"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listDomainMappings(
      request: ListDomainMappingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListDomainMappingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDomainMappings",
        action: {
          (r: ListDomainMappingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.ListDomainMappingsResponse
          in
          return try await self.inner.listDomainMappings(request: r, options: o)
        })
    }

    public func getDomainMapping(
      request: GetDomainMappingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.DomainMapping {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDomainMapping",
        action: {
          (r: GetDomainMappingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.DomainMapping
          in
          return try await self.inner.getDomainMapping(request: r, options: o)
        })
    }

    public func createDomainMapping(
      request: CreateDomainMappingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDomainMapping",
        action: {
          (r: CreateDomainMappingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createDomainMapping(request: r, options: o)
        })
    }

    public func updateDomainMapping(
      request: UpdateDomainMappingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDomainMapping",
        action: {
          (r: UpdateDomainMappingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateDomainMapping(request: r, options: o)
        })
    }

    public func deleteDomainMapping(
      request: DeleteDomainMappingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDomainMapping",
        action: {
          (r: DeleteDomainMappingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteDomainMapping(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
