// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The entrypoint for the application.
public struct Entrypoint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The command to run.
  public var command: OneOf_Command? = nil

  /// Initialize a new instance of `Entrypoint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Entrypoint().with { $0.shell = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case shell = "shell"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var command: OneOf_Command? = nil
    let commandCheckAndSet = {
      if command != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'command'"))
      }
      command = $0
    }
    if let shell = try container.decodeIfPresent(Swift.String.self, forKey: .shell) {
      try commandCheckAndSet(.shell(shell))
    }
    self.command = command
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.command {
      switch choice {
      case .shell(let value):
        try container.encode(value, forKey: .shell)
      }
    }
  }

  /// The command to run.
  public enum OneOf_Command: Codable, Equatable, Sendable {
    /// The format should be a shell command that can be fed to `bash -c`.
    case shell(Swift.String)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.appengine.v1.Entrypoint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
