// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class FirewallLogging: FirewallStub {
    let inner: any FirewallStub
    let logger: Logger

    public init(_ inner: any FirewallStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-appengine-v1"
      logger[metadataKey: "gcp.client.service"] = "appengine"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Firewall"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listIngressRules(
      request: ListIngressRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListIngressRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIngressRules",
        action: {
          (r: ListIngressRulesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.ListIngressRulesResponse
          in
          return try await self.inner.listIngressRules(request: r, options: o)
        })
    }

    public func batchUpdateIngressRules(
      request: BatchUpdateIngressRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.BatchUpdateIngressRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchUpdateIngressRules",
        action: {
          (r: BatchUpdateIngressRulesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.BatchUpdateIngressRulesResponse
          in
          return try await self.inner.batchUpdateIngressRules(request: r, options: o)
        })
    }

    public func createIngressRule(
      request: CreateIngressRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.FirewallRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIngressRule",
        action: {
          (r: CreateIngressRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.FirewallRule
          in
          return try await self.inner.createIngressRule(request: r, options: o)
        })
    }

    public func getIngressRule(
      request: GetIngressRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.FirewallRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIngressRule",
        action: {
          (r: GetIngressRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.FirewallRule
          in
          return try await self.inner.getIngressRule(request: r, options: o)
        })
    }

    public func updateIngressRule(
      request: UpdateIngressRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.FirewallRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIngressRule",
        action: {
          (r: UpdateIngressRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleAppEngineV1.FirewallRule
          in
          return try await self.inner.updateIngressRule(request: r, options: o)
        })
    }

    public func deleteIngressRule(
      request: DeleteIngressRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIngressRule",
        action: {
          (r: DeleteIngressRuleRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteIngressRule(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
