// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A single firewall rule that is evaluated against incoming traffic
/// and provides an action to take on matched requests.
public struct FirewallRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A positive integer between [1, Int32.MaxValue-1] that defines the order of
  /// rule evaluation. Rules with the lowest priority are evaluated first.
  ///
  /// A default rule at priority Int32.MaxValue matches all IPv4 and IPv6 traffic
  /// when no previous rule matches. Only the action of this rule can be modified
  /// by the user.
  public var priority: Swift.Int32 = Swift.Int32()

  /// The action to take on matched requests.
  public var action: FirewallRule.Action = FirewallRule.Action()

  /// IP address or range, defined using CIDR notation, of requests that this
  /// rule applies to. You can use the wildcard character "*" to match all IPs
  /// equivalent to "0/0" and "::/0" together.
  /// Examples: `192.168.1.1` or `192.168.0.0/16` or `2001:db8::/32`
  ///           or `2001:0db8:0000:0042:0000:8a2e:0370:7334`.
  ///
  ///
  /// <p>Truncation will be silently performed on addresses which are not
  /// properly truncated. For example, `1.2.3.4/24` is accepted as the same
  /// address as `1.2.3.0/24`. Similarly, for IPv6, `2001:db8::1/32` is accepted
  /// as the same address as `2001:db8::/32`.
  public var sourceRange: Swift.String = Swift.String()

  /// An optional string description of this rule.
  /// This field has a maximum length of 100 characters.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `FirewallRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FirewallRule().with { $0.priority = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Available actions to take on matching requests.
  public enum Action: Codable, Equatable, Sendable {
    case unspecifiedAction
    /// Matching requests are allowed.
    case allow
    /// Matching requests are denied.
    case deny
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecifiedAction
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecifiedAction: return 0
      case .allow: return 1
      case .deny: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecifiedAction: return "UNSPECIFIED_ACTION"
      case .allow: return "ALLOW"
      case .deny: return "DENY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Action/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED_ACTION": self = .unspecifiedAction
      case "ALLOW": self = .allow
      case "DENY": self = .deny
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Action/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecifiedAction
      case 1: self = .allow
      case 2: self = .deny
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecifiedAction: return try container.encode(0)
      case .allow: return try container.encode(1)
      case .deny: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.FirewallRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
