// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Health checking configuration for VM instances. Unhealthy instances
/// are killed and replaced with new instances. Only applicable for
/// instances in App Engine flexible environment.
public struct HealthCheck: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Whether to explicitly disable health checks for this instance.
  public var disableHealthCheck: Swift.Bool = Swift.Bool()

  /// Host header to send when performing an HTTP health check.
  /// Example: "myapp.appspot.com"
  public var host: Swift.String = Swift.String()

  /// Number of consecutive successful health checks required before receiving
  /// traffic.
  public var healthyThreshold: Swift.UInt32 = Swift.UInt32()

  /// Number of consecutive failed health checks required before removing
  /// traffic.
  public var unhealthyThreshold: Swift.UInt32 = Swift.UInt32()

  /// Number of consecutive failed health checks required before an instance is
  /// restarted.
  public var restartThreshold: Swift.UInt32 = Swift.UInt32()

  /// Interval between health checks.
  public var checkInterval: GoogleCloudWKT.Duration? = nil

  /// Time before the health check is considered failed.
  public var timeout: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `HealthCheck`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HealthCheck().with { $0.disableHealthCheck = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.HealthCheck"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
