// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Health checking configuration for VM instances. Unhealthy instances
/// are killed and replaced with new instances.
public struct LivenessCheck: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The request path.
  public var path: Swift.String = Swift.String()

  /// Host header to send when performing a HTTP Liveness check.
  /// Example: "myapp.appspot.com"
  public var host: Swift.String = Swift.String()

  /// Number of consecutive failed checks required before considering the
  /// VM unhealthy.
  public var failureThreshold: Swift.UInt32 = Swift.UInt32()

  /// Number of consecutive successful checks required before considering
  /// the VM healthy.
  public var successThreshold: Swift.UInt32 = Swift.UInt32()

  /// Interval between health checks.
  public var checkInterval: GoogleCloudWKT.Duration? = nil

  /// Time before the check is considered failed.
  public var timeout: GoogleCloudWKT.Duration? = nil

  /// The initial delay before starting to execute the checks.
  public var initialDelay: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `LivenessCheck`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LivenessCheck().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.LivenessCheck"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
