// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata for the given [google.longrunning.Operation][google.longrunning.Operation].
///
/// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongrunning.Operation
public struct OperationMetadataV1: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// API method that initiated this operation. Example:
  /// `google.appengine.v1.Versions.CreateVersion`.
  ///
  /// @OutputOnly
  public var method: Swift.String = Swift.String()

  /// Time that this operation was created.
  ///
  /// @OutputOnly
  public var insertTime: GoogleCloudWkt.Timestamp? = nil

  /// Time that this operation completed.
  ///
  /// @OutputOnly
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// User who requested this operation.
  ///
  /// @OutputOnly
  public var user: Swift.String = Swift.String()

  /// Name of the resource that this operation is acting on. Example:
  /// `apps/myapp/services/default`.
  ///
  /// @OutputOnly
  public var target: Swift.String = Swift.String()

  /// Ephemeral message that may change every time the operation is polled.
  /// @OutputOnly
  public var ephemeralMessage: Swift.String = Swift.String()

  /// Durable messages that persist on every operation poll.
  /// @OutputOnly
  public var warning: [Swift.String] = []

  /// Metadata specific to the type of operation in progress.
  /// @OutputOnly
  public var methodMetadata: OneOf_MethodMetadata? = nil

  /// Initialize a new instance of `OperationMetadataV1`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadataV1().with { $0.method = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case method = "method"
    case insertTime = "insertTime"
    case endTime = "endTime"
    case user = "user"
    case target = "target"
    case ephemeralMessage = "ephemeralMessage"
    case warning = "warning"
    case createVersionMetadata = "createVersionMetadata"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.method = try container.decode(Swift.String.self, forKey: .method)
    self.insertTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .insertTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .endTime)
    self.user = try container.decode(Swift.String.self, forKey: .user)
    self.target = try container.decode(Swift.String.self, forKey: .target)
    self.ephemeralMessage = try container.decode(Swift.String.self, forKey: .ephemeralMessage)
    self.warning = try container.decode([Swift.String].self, forKey: .warning)

    var methodMetadata: OneOf_MethodMetadata? = nil
    let methodMetadataCheckAndSet = {
      if methodMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'methodMetadata'"))
      }
      methodMetadata = $0
    }
    if let createVersionMetadata = try container.decodeIfPresent(
      CreateVersionMetadataV1?.self, forKey: .createVersionMetadata)
    {
      try methodMetadataCheckAndSet(.createVersionMetadata(createVersionMetadata))
    }
    self.methodMetadata = methodMetadata
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.method, forKey: .method)
    try container.encode(self.insertTime, forKey: .insertTime)
    try container.encode(self.endTime, forKey: .endTime)
    try container.encode(self.user, forKey: .user)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.ephemeralMessage, forKey: .ephemeralMessage)
    try container.encode(self.warning, forKey: .warning)

    if let choice = self.methodMetadata {
      switch choice {
      case .createVersionMetadata(let value):
        try container.encode(value, forKey: .createVersionMetadata)
      }
    }
  }

  /// Metadata specific to the type of operation in progress.
  /// @OutputOnly
  public enum OneOf_MethodMetadata: Codable, Equatable, Sendable {
    indirect case createVersionMetadata(CreateVersionMetadataV1?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.appengine.v1.OperationMetadataV1"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
