// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Machine resources for a version.
public struct Resources: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Number of CPU cores needed.
  public var cpu: Swift.Double = Swift.Double()

  /// Disk size (GB) needed.
  public var diskGb: Swift.Double = Swift.Double()

  /// Memory (GB) needed.
  public var memoryGb: Swift.Double = Swift.Double()

  /// User specified volumes.
  public var volumes: [Volume] = []

  /// The name of the encryption key that is stored in Google Cloud KMS.
  /// Only should be used by Cloud Composer to encrypt the vm disk
  public var kmsKeyReference: Swift.String = Swift.String()

  /// Initialize a new instance of `Resources`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Resources().with { $0.cpu = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Resources"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
