// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Manages services of an application.
///
/// @Snippet(path: "ServicesQuickstart")
public class ServicesClient: Clients.ServicesProtocol {
  let inner: any Clients.ServicesStub

  /// Creates a new `ServicesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ServicesStub = try Clients.ServicesTransport(options)
    inner = Clients.ServicesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ServicesLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists all the services in the application.
  ///
  /// @Snippet(path: "Services_ListServices")
  public func listServices(
    request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListServicesResponse {
    try await self.inner.listServices(request: request, options: options)
  }

  /// Lists all the services in the application.
  ///
  /// @Snippet(path: "Services_ListServices")
  public func listServices(
    byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleAppEngineV1.ListServicesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listServices(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the current configuration of the specified service.
  ///
  /// @Snippet(path: "Services_GetService")
  public func getService(
    request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Service {
    try await self.inner.getService(request: request, options: options)
  }

  /// Updates the configuration of the specified service.
  ///
  /// @Snippet(path: "Services_UpdateService")
  public func updateService(
    request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateService(request: request, options: options)
  }

  /// Updates the configuration of the specified service.
  ///
  /// @Snippet(path: "Services_UpdateService")
  public func updateService(
    withPolling: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Service> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Service>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Service(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateService(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Service>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes the specified service and all enclosed versions.
  ///
  /// @Snippet(path: "Services_DeleteService")
  public func deleteService(
    request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteService(request: request, options: options)
  }

  /// Deletes the specified service and all enclosed versions.
  ///
  /// @Snippet(path: "Services_DeleteService")
  public func deleteService(
    withPolling: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteService(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ServicesClient`.
  ///
  /// To mock `ServicesClient` change your functions to receive
  /// `some ServicesProtocol` or `any ServicesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ServicesProtocol {
    /// See `ServicesClient.listServices`.
    func listServices(request: ListServicesRequest) async throws
      -> GoogleAppEngineV1.ListServicesResponse

    /// See `ServicesClient.listServices`.
    func listServices(
      byItem: ListServicesRequest
    ) throws -> any AsyncSequence<Service, Swift.Error>

    /// See `ServicesClient.getService`.
    func getService(request: GetServiceRequest) async throws -> GoogleAppEngineV1.Service

    /// See `ServicesClient.updateService`.
    func updateService(request: UpdateServiceRequest) async throws -> GoogleLongRunning.Operation

    /// See `ServicesClient.updateService`.
    func updateService(withPolling: UpdateServiceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Service>

    /// See `ServicesClient.deleteService`.
    func deleteService(request: DeleteServiceRequest) async throws -> GoogleLongRunning.Operation

    /// See `ServicesClient.deleteService`.
    func deleteService(withPolling: DeleteServiceRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `ServicesClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ServicesClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ServicesClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ServicesClient.listServices`.
    func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.ListServicesResponse

    /// See `ServicesClient.listServices`.
    func listServices(
      byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Service, Swift.Error>

    /// See `ServicesClient.getService`.
    func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleAppEngineV1.Service

    /// See `ServicesClient.updateService`.
    func updateService(
      request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ServicesClient.updateService`.
    func updateService(
      withPolling: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Service>

    /// See `ServicesClient.deleteService`.
    func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ServicesClient.deleteService`.
    func deleteService(
      withPolling: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ServicesClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ServicesClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.ServicesProtocol {
  public func listServices(request: ListServicesRequest) async throws
    -> GoogleAppEngineV1.ListServicesResponse
  {
    try await self.listServices(request: request, options: .init())
  }

  public func listServices(
    request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.ListServicesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listServices(
    byItem: ListServicesRequest
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    try self.listServices(byItem: byItem, options: .init())
  }

  public func listServices(
    byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Service, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleAppEngineV1.ListServicesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getService(request: GetServiceRequest) async throws -> GoogleAppEngineV1.Service {
    try await self.getService(request: request, options: .init())
  }

  public func getService(
    request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleAppEngineV1.Service {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateService(request: UpdateServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateService(request: request, options: .init())
  }

  public func updateService(
    request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateService(withPolling: UpdateServiceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Service>
  {
    try await self.updateService(withPolling: withPolling, options: .init())
  }

  public func updateService(
    withPolling: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Service> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Service>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteService(request: DeleteServiceRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteService(request: request, options: .init())
  }

  public func deleteService(
    request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteService(withPolling: DeleteServiceRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteService(withPolling: withPolling, options: .init())
  }

  public func deleteService(
    withPolling: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
