// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A Service resource is a logical component of an application that can share
/// state and communicate in a secure fashion with other services.
/// For example, an application that handles customer requests might
/// include separate services to handle tasks such as backend data
/// analysis or API requests from mobile devices. Each service has a
/// collection of versions that define a specific set of code used to
/// implement the functionality of that service.
public struct Service: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Full path to the Service resource in the API.
  /// Example: `apps/myapp/services/default`.
  ///
  /// @OutputOnly
  public var name: Swift.String = Swift.String()

  /// Relative name of the service within the application.
  /// Example: `default`.
  ///
  /// @OutputOnly
  public var id: Swift.String = Swift.String()

  /// Mapping that defines fractional HTTP traffic diversion to
  /// different versions within the service.
  public var split: TrafficSplit? = nil

  /// A set of labels to apply to this service. Labels are key/value pairs that
  /// describe the service and all resources that belong to it (e.g.,
  /// versions). The labels can be used to search and group resources, and are
  /// propagated to the usage and billing reports, enabling fine-grain analysis
  /// of costs. An example of using labels is to tag resources belonging to
  /// different environments (e.g., "env=prod", "env=qa").
  ///
  /// <p>Label keys and values can be no longer than 63 characters and can only
  /// contain lowercase letters, numeric characters, underscores, dashes, and
  /// international characters. Label keys must start with a lowercase letter
  /// or an international character. Each service can have at most 32 labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Ingress settings for this service. Will apply to all versions.
  public var networkSettings: NetworkSettings? = nil

  /// Initialize a new instance of `Service`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Service().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Service"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
