// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Files served directly to the user for a given URL, such as images, CSS
/// stylesheets, or JavaScript source files. Static file handlers describe which
/// files in the application directory are static files, and which URLs serve
/// them.
public struct StaticFilesHandler: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Path to the static files matched by the URL pattern, from the
  /// application root directory. The path can refer to text matched in groupings
  /// in the URL pattern.
  public var path: Swift.String = Swift.String()

  /// Regular expression that matches the file paths for all files that should be
  /// referenced by this handler.
  public var uploadPathRegex: Swift.String = Swift.String()

  /// HTTP headers to use for all responses from these URLs.
  public var httpHeaders: [Swift.String: Swift.String] = [:]

  /// MIME type used to serve all files served by this handler.
  ///
  /// Defaults to file-specific MIME types, which are derived from each file's
  /// filename extension.
  public var mimeType: Swift.String = Swift.String()

  /// Time a static file served by this handler should be cached
  /// by web proxies and browsers.
  public var expiration: GoogleCloudWkt.Duration? = nil

  /// Whether this handler should match the request if the file
  /// referenced by the handler does not exist.
  public var requireMatchingFile: Swift.Bool = Swift.Bool()

  /// Whether files should also be uploaded as code data. By default, files
  /// declared in static file handlers are uploaded as static
  /// data and are only served to end users; they cannot be read by the
  /// application. If enabled, uploads are charged against both your code and
  /// static data storage resource quotas.
  public var applicationReadable: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `StaticFilesHandler`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StaticFilesHandler().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.StaticFilesHandler"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
