// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Traffic routing configuration for versions within a single service. Traffic
/// splits define how traffic directed to the service is assigned to versions.
public struct TrafficSplit: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Mechanism used to determine which version a request is sent to.
  /// The traffic selection algorithm will
  /// be stable for either type until allocations are changed.
  public var shardBy: TrafficSplit.ShardBy = TrafficSplit.ShardBy()

  /// Mapping from version IDs within the service to fractional
  /// (0.000, 1] allocations of traffic for that version. Each version can
  /// be specified only once, but some versions in the service may not
  /// have any traffic allocation. Services that have traffic allocated
  /// cannot be deleted until either the service is deleted or
  /// their traffic allocation is removed. Allocations must sum to 1.
  /// Up to two decimal place precision is supported for IP-based splits and
  /// up to three decimal places is supported for cookie-based splits.
  public var allocations: [Swift.String: Swift.Double] = [:]

  /// Initialize a new instance of `TrafficSplit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TrafficSplit().with { $0.shardBy = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Available sharding mechanisms.
  public enum ShardBy: Codable, Equatable, Sendable {
    /// Diversion method unspecified.
    case unspecified
    /// Diversion based on a specially named cookie, "GOOGAPPUID." The cookie
    /// must be set by the application itself or no diversion will occur.
    case cookie
    /// Diversion based on applying the modulus operation to a fingerprint
    /// of the IP address.
    case ip
    /// Diversion based on weighted random assignment. An incoming request is
    /// randomly routed to a version in the traffic split, with probability
    /// proportional to the version's traffic share.
    case random
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cookie: return 1
      case .ip: return 2
      case .random: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .cookie: return "COOKIE"
      case .ip: return "IP"
      case .random: return "RANDOM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ShardBy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "COOKIE": self = .cookie
      case "IP": self = .ip
      case "RANDOM": self = .random
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ShardBy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cookie
      case 2: self = .ip
      case 3: self = .random
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cookie: return try container.encode(1)
      case .ip: return try container.encode(2)
      case .random: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.TrafficSplit"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
