// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Rules to match an HTTP request and dispatch that request to a service.
public struct UrlDispatchRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Domain name to match against. The wildcard "`*`" is supported if
  /// specified before a period: "`*.`".
  ///
  /// Defaults to matching all domains: "`*`".
  public var domain: Swift.String = Swift.String()

  /// Pathname within the host. Must start with a "`/`". A
  /// single "`*`" can be included at the end of the path.
  ///
  /// The sum of the lengths of the domain and path may not
  /// exceed 100 characters.
  public var path: Swift.String = Swift.String()

  /// Resource ID of a service in this application that should
  /// serve the matched request. The service must already
  /// exist. Example: `default`.
  public var service: Swift.String = Swift.String()

  /// Initialize a new instance of `UrlDispatchRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UrlDispatchRule().with { $0.domain = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.UrlDispatchRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
