// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// URL pattern and description of how the URL should be handled. App Engine can
/// handle URLs by executing application code or by serving static files
/// uploaded with the version, such as images, CSS, or JavaScript.
public struct UrlMap: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// URL prefix. Uses regular expression syntax, which means regexp
  /// special characters must be escaped, but should not contain groupings.
  /// All URLs that begin with this prefix are handled by this handler, using the
  /// portion of the URL after the prefix as part of the file path.
  public var urlRegex: Swift.String = Swift.String()

  /// Security (HTTPS) enforcement for this URL.
  public var securityLevel: SecurityLevel = SecurityLevel()

  /// Level of login required to access this resource. Not supported for Node.js
  /// in the App Engine standard environment.
  public var login: LoginRequirement = LoginRequirement()

  /// Action to take when users access resources that require
  /// authentication. Defaults to `redirect`.
  public var authFailAction: AuthFailAction = AuthFailAction()

  /// `30x` code to use when performing redirects for the `secure` field.
  /// Defaults to `302`.
  public var redirectHttpResponseCode: UrlMap.RedirectHttpResponseCode =
    UrlMap.RedirectHttpResponseCode()

  /// Type of handler for this URL pattern.
  public var handlerType: OneOf_HandlerType? = nil

  /// Initialize a new instance of `UrlMap`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UrlMap().with { $0.urlRegex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case urlRegex = "urlRegex"
    case staticFiles = "staticFiles"
    case script = "script"
    case apiEndpoint = "apiEndpoint"
    case securityLevel = "securityLevel"
    case login = "login"
    case authFailAction = "authFailAction"
    case redirectHttpResponseCode = "redirectHttpResponseCode"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.urlRegex = try container.decode(Swift.String.self, forKey: .urlRegex)
    self.securityLevel = try container.decode(SecurityLevel.self, forKey: .securityLevel)
    self.login = try container.decode(LoginRequirement.self, forKey: .login)
    self.authFailAction = try container.decode(AuthFailAction.self, forKey: .authFailAction)
    self.redirectHttpResponseCode = try container.decode(
      UrlMap.RedirectHttpResponseCode.self, forKey: .redirectHttpResponseCode)

    var handlerType: OneOf_HandlerType? = nil
    let handlerTypeCheckAndSet = {
      if handlerType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'handlerType'"))
      }
      handlerType = $0
    }
    if let staticFiles = try container.decodeIfPresent(
      StaticFilesHandler?.self, forKey: .staticFiles)
    {
      try handlerTypeCheckAndSet(.staticFiles(staticFiles))
    }
    if let script = try container.decodeIfPresent(ScriptHandler?.self, forKey: .script) {
      try handlerTypeCheckAndSet(.script(script))
    }
    if let apiEndpoint = try container.decodeIfPresent(
      ApiEndpointHandler?.self, forKey: .apiEndpoint)
    {
      try handlerTypeCheckAndSet(.apiEndpoint(apiEndpoint))
    }
    self.handlerType = handlerType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.urlRegex, forKey: .urlRegex)
    try container.encode(self.securityLevel, forKey: .securityLevel)
    try container.encode(self.login, forKey: .login)
    try container.encode(self.authFailAction, forKey: .authFailAction)
    try container.encode(self.redirectHttpResponseCode, forKey: .redirectHttpResponseCode)

    if let choice = self.handlerType {
      switch choice {
      case .staticFiles(let value):
        try container.encode(value, forKey: .staticFiles)
      case .script(let value):
        try container.encode(value, forKey: .script)
      case .apiEndpoint(let value):
        try container.encode(value, forKey: .apiEndpoint)
      }
    }
  }

  /// Redirect codes.
  public enum RedirectHttpResponseCode: Codable, Equatable, Sendable {
    /// Not specified. `302` is assumed.
    case unspecified
    /// `301 Moved Permanently` code.
    case redirectHttpResponseCode301
    /// `302 Moved Temporarily` code.
    case redirectHttpResponseCode302
    /// `303 See Other` code.
    case redirectHttpResponseCode303
    /// `307 Temporary Redirect` code.
    case redirectHttpResponseCode307
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .redirectHttpResponseCode301: return 1
      case .redirectHttpResponseCode302: return 2
      case .redirectHttpResponseCode303: return 3
      case .redirectHttpResponseCode307: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED"
      case .redirectHttpResponseCode301: return "REDIRECT_HTTP_RESPONSE_CODE_301"
      case .redirectHttpResponseCode302: return "REDIRECT_HTTP_RESPONSE_CODE_302"
      case .redirectHttpResponseCode303: return "REDIRECT_HTTP_RESPONSE_CODE_303"
      case .redirectHttpResponseCode307: return "REDIRECT_HTTP_RESPONSE_CODE_307"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "REDIRECT_HTTP_RESPONSE_CODE_UNSPECIFIED": self = .unspecified
      case "REDIRECT_HTTP_RESPONSE_CODE_301": self = .redirectHttpResponseCode301
      case "REDIRECT_HTTP_RESPONSE_CODE_302": self = .redirectHttpResponseCode302
      case "REDIRECT_HTTP_RESPONSE_CODE_303": self = .redirectHttpResponseCode303
      case "REDIRECT_HTTP_RESPONSE_CODE_307": self = .redirectHttpResponseCode307
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .redirectHttpResponseCode301
      case 2: self = .redirectHttpResponseCode302
      case 3: self = .redirectHttpResponseCode303
      case 4: self = .redirectHttpResponseCode307
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .redirectHttpResponseCode301: return try container.encode(1)
      case .redirectHttpResponseCode302: return try container.encode(2)
      case .redirectHttpResponseCode303: return try container.encode(3)
      case .redirectHttpResponseCode307: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of handler for this URL pattern.
  public enum OneOf_HandlerType: Codable, Equatable, Sendable {
    /// Returns the contents of a file, such as an image, as the response.
    indirect case staticFiles(StaticFilesHandler?)
    /// Executes a script to handle the requests that match this URL
    /// pattern. Only the `auto` value is supported for Node.js in the
    /// App Engine standard environment, for example `"script": "auto"`.
    indirect case script(ScriptHandler?)
    /// Uses API Endpoints to handle requests.
    indirect case apiEndpoint(ApiEndpointHandler?)
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.appengine.v1.UrlMap" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
