// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Version resource is a specific set of source code and configuration files
/// that are deployed into a service.
public struct Version: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Full path to the Version resource in the API.  Example:
  /// `apps/myapp/services/default/versions/v1`.
  ///
  /// @OutputOnly
  public var name: Swift.String = Swift.String()

  /// Relative name of the version within the service.  Example: `v1`.
  /// Version names can contain only lowercase letters, numbers, or hyphens.
  /// Reserved names: "default", "latest", and any name with the prefix "ah-".
  public var id: Swift.String = Swift.String()

  /// Before an application can receive email or XMPP messages, the application
  /// must be configured to enable the service.
  public var inboundServices: [InboundServiceType] = []

  /// Instance class that is used to run this version. Valid values are:
  ///
  /// * AutomaticScaling: `F1`, `F2`, `F4`, `F4_1G`
  /// * ManualScaling or BasicScaling: `B1`, `B2`, `B4`, `B8`, `B4_1G`
  ///
  /// Defaults to `F1` for AutomaticScaling and `B1` for ManualScaling or
  /// BasicScaling.
  public var instanceClass: Swift.String = Swift.String()

  /// Extra network settings.
  /// Only applicable in the App Engine flexible environment.
  public var network: Network? = nil

  /// The Google Compute Engine zones that are supported by this version in the
  /// App Engine flexible environment. Deprecated.
  public var zones: [Swift.String] = []

  /// Machine resources for this version.
  /// Only applicable in the App Engine flexible environment.
  public var resources: Resources? = nil

  /// Desired runtime. Example: `python27`.
  public var runtime: Swift.String = Swift.String()

  /// The channel of the runtime to use. Only available for some
  /// runtimes. Defaults to the `default` channel.
  public var runtimeChannel: Swift.String = Swift.String()

  /// Whether multiple requests can be dispatched to this version at once.
  public var threadsafe: Swift.Bool = Swift.Bool()

  /// Whether to deploy this version in a container on a virtual machine.
  public var vm: Swift.Bool = Swift.Bool()

  /// Allows App Engine second generation runtimes to access the legacy bundled
  /// services.
  public var appEngineApis: Swift.Bool = Swift.Bool()

  /// Metadata settings that are supplied to this version to enable
  /// beta runtime features.
  public var betaSettings: [Swift.String: Swift.String] = [:]

  /// App Engine execution environment for this version.
  ///
  /// Defaults to `standard`.
  public var env: Swift.String = Swift.String()

  /// Current serving status of this version. Only the versions with a
  /// `SERVING` status create instances and can be billed.
  ///
  /// `SERVING_STATUS_UNSPECIFIED` is an invalid value. Defaults to `SERVING`.
  public var servingStatus: ServingStatus = ServingStatus()

  /// Email address of the user who created this version.
  ///
  /// @OutputOnly
  public var createdBy: Swift.String = Swift.String()

  /// Time that this version was created.
  ///
  /// @OutputOnly
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Total size in bytes of all the files that are included in this version
  /// and currently hosted on the App Engine disk.
  ///
  /// @OutputOnly
  public var diskUsageBytes: Swift.Int64 = Swift.Int64()

  /// The version of the API in the given runtime environment. Please see the
  /// app.yaml reference for valid values at
  /// https://cloud.google.com/appengine/docs/standard/<language>/config/appref
  public var runtimeApiVersion: Swift.String = Swift.String()

  /// The path or name of the app's main executable.
  public var runtimeMainExecutablePath: Swift.String = Swift.String()

  /// The identity that the deployed version will run as.
  /// Admin API will use the App Engine Appspot service account as default if
  /// this field is neither provided in app.yaml file nor through CLI flag.
  public var serviceAccount: Swift.String = Swift.String()

  /// An ordered list of URL-matching patterns that should be applied to incoming
  /// requests. The first matching URL handles the request and other request
  /// handlers are not attempted.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var handlers: [UrlMap] = []

  /// Custom static error pages. Limited to 10KB per page.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var errorHandlers: [ErrorHandler] = []

  /// Configuration for third-party Python runtime libraries that are required
  /// by the application.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var libraries: [Library] = []

  /// Serving configuration for
  /// [Google Cloud Endpoints](https://cloud.google.com/appengine/docs/python/endpoints/).
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var apiConfig: ApiConfigHandler? = nil

  /// Environment variables available to the application.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var envVariables: [Swift.String: Swift.String] = [:]

  /// Environment variables available to the build environment.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var buildEnvVariables: [Swift.String: Swift.String] = [:]

  /// Duration that static files should be cached by web proxies and browsers.
  /// Only applicable if the corresponding
  /// [StaticFilesHandler](https://cloud.google.com/appengine/docs/admin-api/reference/rest/v1/apps.services.versions#StaticFilesHandler)
  /// does not specify its own expiration time.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var defaultExpiration: GoogleCloudWKT.Duration? = nil

  /// Configures health checking for instances. Unhealthy instances are
  /// stopped and replaced with new instances.
  /// Only applicable in the App Engine flexible environment.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var healthCheck: HealthCheck? = nil

  /// Configures readiness health checking for instances.
  /// Unhealthy instances are not put into the backend traffic rotation.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var readinessCheck: ReadinessCheck? = nil

  /// Configures liveness health checking for instances.
  /// Unhealthy instances are stopped and replaced with new instances
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var livenessCheck: LivenessCheck? = nil

  /// Files that match this pattern will not be built into this version.
  /// Only applicable for Go runtimes.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var nobuildFilesRegex: Swift.String = Swift.String()

  /// Code and application artifacts that make up this version.
  ///
  /// Only returned in `GET` requests if `view=FULL` is set.
  public var deployment: Deployment? = nil

  /// Serving URL for this version. Example:
  /// "https://myversion-dot-myservice-dot-myapp.appspot.com"
  ///
  /// @OutputOnly
  public var versionUrl: Swift.String = Swift.String()

  /// Cloud Endpoints configuration.
  ///
  /// If endpoints_api_service is set, the Cloud Endpoints Extensible Service
  /// Proxy will be provided to serve the API implemented by the app.
  public var endpointsApiService: EndpointsApiService? = nil

  /// The entrypoint for the application.
  public var entrypoint: Entrypoint? = nil

  /// Enables VPC connectivity for standard apps.
  public var vpcAccessConnector: VpcAccessConnector? = nil

  /// Controls how instances are created, scaled, and reaped.
  ///
  /// Defaults to `AutomaticScaling`.
  public var scaling: OneOf_Scaling? = nil

  /// Initialize a new instance of `Version`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Version().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case id = "id"
    case automaticScaling = "automaticScaling"
    case basicScaling = "basicScaling"
    case manualScaling = "manualScaling"
    case inboundServices = "inboundServices"
    case instanceClass = "instanceClass"
    case network = "network"
    case zones = "zones"
    case resources = "resources"
    case runtime = "runtime"
    case runtimeChannel = "runtimeChannel"
    case threadsafe = "threadsafe"
    case vm = "vm"
    case appEngineApis = "appEngineApis"
    case betaSettings = "betaSettings"
    case env = "env"
    case servingStatus = "servingStatus"
    case createdBy = "createdBy"
    case createTime = "createTime"
    case diskUsageBytes = "diskUsageBytes"
    case runtimeApiVersion = "runtimeApiVersion"
    case runtimeMainExecutablePath = "runtimeMainExecutablePath"
    case serviceAccount = "serviceAccount"
    case handlers = "handlers"
    case errorHandlers = "errorHandlers"
    case libraries = "libraries"
    case apiConfig = "apiConfig"
    case envVariables = "envVariables"
    case buildEnvVariables = "buildEnvVariables"
    case defaultExpiration = "defaultExpiration"
    case healthCheck = "healthCheck"
    case readinessCheck = "readinessCheck"
    case livenessCheck = "livenessCheck"
    case nobuildFilesRegex = "nobuildFilesRegex"
    case deployment = "deployment"
    case versionUrl = "versionUrl"
    case endpointsApiService = "endpointsApiService"
    case entrypoint = "entrypoint"
    case vpcAccessConnector = "vpcAccessConnector"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.inboundServices = try container.decode([InboundServiceType].self, forKey: .inboundServices)
    self.instanceClass = try container.decode(Swift.String.self, forKey: .instanceClass)
    self.network = try container.decodeIfPresent(Network.self, forKey: .network)
    self.zones = try container.decode([Swift.String].self, forKey: .zones)
    self.resources = try container.decodeIfPresent(Resources.self, forKey: .resources)
    self.runtime = try container.decode(Swift.String.self, forKey: .runtime)
    self.runtimeChannel = try container.decode(Swift.String.self, forKey: .runtimeChannel)
    self.threadsafe = try container.decode(Swift.Bool.self, forKey: .threadsafe)
    self.vm = try container.decode(Swift.Bool.self, forKey: .vm)
    self.appEngineApis = try container.decode(Swift.Bool.self, forKey: .appEngineApis)
    self.betaSettings = try container.decode(
      [Swift.String: Swift.String].self, forKey: .betaSettings)
    self.env = try container.decode(Swift.String.self, forKey: .env)
    self.servingStatus = try container.decode(ServingStatus.self, forKey: .servingStatus)
    self.createdBy = try container.decode(Swift.String.self, forKey: .createdBy)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.diskUsageBytes = try container.decode(Swift.Int64.self, forKey: .diskUsageBytes)
    self.runtimeApiVersion = try container.decode(Swift.String.self, forKey: .runtimeApiVersion)
    self.runtimeMainExecutablePath = try container.decode(
      Swift.String.self, forKey: .runtimeMainExecutablePath)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.handlers = try container.decode([UrlMap].self, forKey: .handlers)
    self.errorHandlers = try container.decode([ErrorHandler].self, forKey: .errorHandlers)
    self.libraries = try container.decode([Library].self, forKey: .libraries)
    self.apiConfig = try container.decodeIfPresent(ApiConfigHandler.self, forKey: .apiConfig)
    self.envVariables = try container.decode(
      [Swift.String: Swift.String].self, forKey: .envVariables)
    self.buildEnvVariables = try container.decode(
      [Swift.String: Swift.String].self, forKey: .buildEnvVariables)
    self.defaultExpiration = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .defaultExpiration)
    self.healthCheck = try container.decodeIfPresent(HealthCheck.self, forKey: .healthCheck)
    self.readinessCheck = try container.decodeIfPresent(
      ReadinessCheck.self, forKey: .readinessCheck)
    self.livenessCheck = try container.decodeIfPresent(LivenessCheck.self, forKey: .livenessCheck)
    self.nobuildFilesRegex = try container.decode(Swift.String.self, forKey: .nobuildFilesRegex)
    self.deployment = try container.decodeIfPresent(Deployment.self, forKey: .deployment)
    self.versionUrl = try container.decode(Swift.String.self, forKey: .versionUrl)
    self.endpointsApiService = try container.decodeIfPresent(
      EndpointsApiService.self, forKey: .endpointsApiService)
    self.entrypoint = try container.decodeIfPresent(Entrypoint.self, forKey: .entrypoint)
    self.vpcAccessConnector = try container.decodeIfPresent(
      VpcAccessConnector.self, forKey: .vpcAccessConnector)

    var scaling: OneOf_Scaling? = nil
    let scalingCheckAndSet = {
      if scaling != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'scaling'"))
      }
      scaling = $0
    }
    if let automaticScaling = try container.decodeIfPresent(
      AutomaticScaling?.self, forKey: .automaticScaling)
    {
      try scalingCheckAndSet(.automaticScaling(automaticScaling))
    }
    if let basicScaling = try container.decodeIfPresent(BasicScaling?.self, forKey: .basicScaling) {
      try scalingCheckAndSet(.basicScaling(basicScaling))
    }
    if let manualScaling = try container.decodeIfPresent(
      ManualScaling?.self, forKey: .manualScaling)
    {
      try scalingCheckAndSet(.manualScaling(manualScaling))
    }
    self.scaling = scaling
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.inboundServices, forKey: .inboundServices)
    try container.encode(self.instanceClass, forKey: .instanceClass)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.zones, forKey: .zones)
    try container.encode(self.resources, forKey: .resources)
    try container.encode(self.runtime, forKey: .runtime)
    try container.encode(self.runtimeChannel, forKey: .runtimeChannel)
    try container.encode(self.threadsafe, forKey: .threadsafe)
    try container.encode(self.vm, forKey: .vm)
    try container.encode(self.appEngineApis, forKey: .appEngineApis)
    try container.encode(self.betaSettings, forKey: .betaSettings)
    try container.encode(self.env, forKey: .env)
    try container.encode(self.servingStatus, forKey: .servingStatus)
    try container.encode(self.createdBy, forKey: .createdBy)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.diskUsageBytes, forKey: .diskUsageBytes)
    try container.encode(self.runtimeApiVersion, forKey: .runtimeApiVersion)
    try container.encode(self.runtimeMainExecutablePath, forKey: .runtimeMainExecutablePath)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.handlers, forKey: .handlers)
    try container.encode(self.errorHandlers, forKey: .errorHandlers)
    try container.encode(self.libraries, forKey: .libraries)
    try container.encode(self.apiConfig, forKey: .apiConfig)
    try container.encode(self.envVariables, forKey: .envVariables)
    try container.encode(self.buildEnvVariables, forKey: .buildEnvVariables)
    try container.encode(self.defaultExpiration, forKey: .defaultExpiration)
    try container.encode(self.healthCheck, forKey: .healthCheck)
    try container.encode(self.readinessCheck, forKey: .readinessCheck)
    try container.encode(self.livenessCheck, forKey: .livenessCheck)
    try container.encode(self.nobuildFilesRegex, forKey: .nobuildFilesRegex)
    try container.encode(self.deployment, forKey: .deployment)
    try container.encode(self.versionUrl, forKey: .versionUrl)
    try container.encode(self.endpointsApiService, forKey: .endpointsApiService)
    try container.encode(self.entrypoint, forKey: .entrypoint)
    try container.encode(self.vpcAccessConnector, forKey: .vpcAccessConnector)

    if let choice = self.scaling {
      switch choice {
      case .automaticScaling(let value):
        try container.encode(value, forKey: .automaticScaling)
      case .basicScaling(let value):
        try container.encode(value, forKey: .basicScaling)
      case .manualScaling(let value):
        try container.encode(value, forKey: .manualScaling)
      }
    }
  }

  /// Controls how instances are created, scaled, and reaped.
  ///
  /// Defaults to `AutomaticScaling`.
  public enum OneOf_Scaling: Codable, Equatable, Sendable {
    /// Automatic scaling is based on request rate, response latencies, and other
    /// application metrics. Instances are dynamically created and destroyed as
    /// needed in order to handle traffic.
    indirect case automaticScaling(AutomaticScaling?)
    /// A service with basic scaling will create an instance when the application
    /// receives a request. The instance will be turned down when the app becomes
    /// idle. Basic scaling is ideal for work that is intermittent or driven by
    /// user activity.
    indirect case basicScaling(BasicScaling?)
    /// A service with manual scaling runs continuously, allowing you to perform
    /// complex initialization and rely on the state of its memory over time.
    /// Manually scaled versions are sometimes referred to as "backends".
    indirect case manualScaling(ManualScaling?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.appengine.v1.Version"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
